id = "ghoti"
name = "Ghoti"
description = "Ghoti language support: syntax highlighting and the ghoti lsp language server."
version = "0.3.0"
schema_version = 1
authors = ["Trevor Swan"]
repository = "https://github.com/trevorswan11/ghoti"

[language_servers.ghoti-lsp]
name = "ghoti lsp"
language = "Ghoti"

[grammars.ghoti]
repository = "https://github.com/trevorswan11/tree-sitter-ghoti"
commit = "38fbb20b7470ff36576f2a8a691eeb0d2e46a387"
