id = "ghoti"
name = "Ghoti"
description = "Ghoti language support: syntax highlighting and the ghoti lsp language server."
version = "0.4.0"
schema_version = 1
authors = ["Trevor Swan"]
repository = "https://github.com/trevorswan11/ghoti"

[language_servers.ghoti-lsp]
name = "ghoti lsp"
language = "Ghoti"

[grammars.ghoti]
repository = "https://github.com/trevorswan11/tree-sitter-ghoti"
commit = "8d1b51a15a4d9f74c061a7e7c2aaec09a928b1be"
